### ISSUE TITLE
Armor properties rarity are not correctly decrypted

### ISSUE THREAD

**Issue by AireAyquaza** [HellPie/DungeonTools#3]
Hi ! I just found an issue about unique armor decryption, the armor json contains an `armorproperties` section witch list armor properties an their rarity.

Actually the rarity of armor properties is not correctly decrypted, you can get an unique armor property in-game an after decrypting it, you get a common armor property. If you encrypt the json file, the game will display a common armor property instead of an unique one. Actually i think there is no armor property with a 'rare' rarity, only common and unique

**How to reproduce ?**
- Decrypt your save file
- Replace the item at inventoryIndex = 0 by the following : [SpelunkersArmor_Unique1.txt](https://github.com/HellPie/DungeonTools/files/5070693/SpelunkersArmor_Unique1.txt) and encrypt your save game
- Launch game and see the rarity of the first armor property, it's unique
- Quit game, decrypt your save file and encrypt your save game once again
- Launch game and see the changed rarity, it's common

**Comment by ZingBallyhoo** [comment]
please try launching the game the second time without modifying the save again. the tool doesn't parse or modify any json

**Comment by HellPie** [comment]
DTools doesn't parse the content of the save files, it just takes the whole file and either encrypts it or decrypts it. Check that you're not overwriting existing files and use the appropriate CLI flag (`--overwrite=false`) if that's the case.
