### ISSUE TITLE
Launching

### ISSUE THREAD

**Issue by kahhyl** [HellPie/DungeonTools#4]
I could be an idiot but I'm trying to follow your Automagic Mode but I cant seem to find the executable file. I also tried to follow the Manual mode and it kept telling me that .\dtool.exe didnt exist. Sorry if I'm an inconvenience.

**Comment by ZingBallyhoo** [comment]
download from https://github.com/HellPie/DungeonTools/releases/download/1.5.0-stable/DungeonTools_1.5.0-Stable_MCD-1.3.2.0.zip

the file here is called dtools.exe

**Comment by kahhyl** [comment]
Thank you, I dont know why it wasn't appearing for me before, but now it is.
